### ISSUE TITLE
Feature: Replay client requests

### ISSUE THREAD

**Issue by bbros-dev** [rjframe/surf-vcr#1]
Thanks for all the effort that has gone into this crate and for making it open source.

We're reviewing surf for a use case we didn't see in the doc or examples folders: Replaying the client requests.

Is this currently possible? We saw the documented case showing a case where the server response is loaded to be replayed, but not the corollary.

If not currently possible, would it be within the scope of surf-vcr?

In case it helps, some context:

- The VCR files will come from Ruby's [VCR](https://github.com/vcr/vcr) (not us specifically but we expect others), be hand crafted or be recorded by surf-vcr.
- The ambition is that it is possible to create a [Taurus](https://gettaurus.org/) like load generator, focussed only on Rust, so hopefully much more performant.  Initial highly experimental effort is underway in [Swanling](https://github.com/begleybrothers/swanling)
- In that context it will be **critical** to be able to schedule making  async requests using [Tokio's `interval`](https://docs.rs/tokio/1.8.1/tokio/time/fn.interval.html) and [`interval_at`](https://docs.rs/tokio/1.8.1/tokio/time/fn.interval_at.html), which we'd implement using the observer pattern - [something like this](https://stackoverflow.com/a/37573345)

On the last point we're not expecting the Tokio `interval` or async observer functionality be added to surf-vcr, rather we just hope that nothing blocks or conflicts with it being used.  Obviously as an experimental effort and things are in flux but we think request replay in surf-vcr would be very useful.

When the replay file contains requests and responses there are distinct use cases for surf-vcr ignoring the response in the replay file, and recording the response in a new/separate file.  We could also imagine someone wanting surf to exhibit the opposite behavior and error out if the response does not match that in the replay file.  Maybe configurable behavior.

We understand that is quite a wish list, so we put it forward more to solicit if your road map envisions anything like that.

**Comment by rjframe** [comment]
Hi. I'm not sure I understand what you're asking for. Is the following correct?

> You want to test a server against a range of requests; send the request, then ensure the server provides the response in the recording.

If so, it's not something I intend to add -- I don't know that I could do it cleanly, and my focus is strictly in testing clients. You should be able to fork/rewrite this to do it pretty easily; you'd be looking at the `handle` method of the `VcrMiddleware`. The match's `Record` branch probably wouldn't need to change, just the `Replay` -- instead of returning the deserialized response, you'd send it on then check the final response against the deserialized response. Something like (untested, may not even build):

```rust
match self.mode {
    VcrMode::Replay {
        let mut res = next.run(req, client).await?;
        let response = VcrResponse::try_from_response(&mut res).await?;

        let cassettes = CASSETTES.get().unwrap().read().await;
        let (requests, responses) = &cassettes[&self.file];

        match requests.iter().position(|x| x == &request) {
            Some(pos) => {
                if response == responses[pos] {
                     // Responses match
                } else {
                    // Responses don't match
                }
            },
            None => Err(surf::Error::new(
                StatusCode::NotFound,
                VcrError::Lookup(Request::from(request))
            )),
        }
    }
}
```

**Comment by bbros-dev** [comment]
@rjframe Thanks for the helpful pointer - we don't care about comparing the response, but imagined others might.  What you've given above looks sufficient.  

I'll close this issue and implement that in our code.  If you decide to add it re-open and we'll update you on any progress in our experiment.
